# Generated by Django 4.2.30 on 2026-09-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
